name: Docker Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # Step 2: Build Docker image
      - name: Build Docker image
        run: docker build -t aplang-website:latest .

      # Step 3: Create Stage Directory
      - name: Create Stage Directory
        run: mkdir -p ~/docker-images

      # Step 4: Save Docker image to tar
      - name: Save Docker image
        run: docker save --output ~/docker-images/aplang-website.tar aplang-website:latest

      # Step 5: Peek into the files
      - name: Peek Files
        run: ls -la ~/docker-images

      # Step 6: Set up SSH key for SCP
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
      - name: Remove old archive file
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
            rm ~/docker-images/aplang-website.tar
          EOF
      # Step 7: Copy Docker image to remote server using SCP
      - name: SCP Docker Image to Server
        run: |
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r ~/docker-images root@${{ secrets.DROPLET_IP }}:~/docker-images

      # Step 8: SSH into the server and load/run the Docker image
      - name: Load and Run Docker Image on Server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no root@${{ secrets.DROPLET_IP }} << 'EOF'
            docker load -i ~/docker-images/aplang-website.tar
            docker stop aplang-website || true
            docker rm aplang-website || true
            docker run -d --name aplang-website -p 3000:3000 aplang-website:latest
          EOF
